export const articlesData = [
  {
    id: 1,
    title: "The Future of Artificial Intelligence",
    slug: "the-future-of-artificial-intelligence",
    author: "Sarah Johnson",
    image: "https://placehold.co/600x400",
    date: "2024-01-15",
    category: "Technology",
    summary: "Exploring the latest developments in AI and machine learning",
    readTime: 5,
    tags: ["AI", "Technology", "Future"],
    likes: 245,
  },
  {
    id: 2,
    title: "Sustainable Living in 2024",
    slug: "sustainable-living-in-2024",
    author: "Michael Chen",
    image: "https://placehold.co/600x400",
    date: "2024-01-14",
    category: "Lifestyle",
    summary: "Tips for reducing your carbon footprint",
    readTime: 8,
    tags: ["Environment", "Lifestyle", "Sustainability"],
    likes: 189,
  },
  {
    id: 3,
    title: "Modern Web Development Practices",
    slug: "modern-web-development-practices",
    author: "Alex Rodriguez",
    image: "https://placehold.co/600x400",
    date: "2024-01-14",
    category: "Programming",
    summary: "Best practices for modern web development",
    readTime: 10,
    tags: ["Web Development", "Programming", "Tech", "Art"],
    likes: 322,
  },
  {
    id: 4,
    title: "Healthy Eating Habits",
    slug: "healthy-eating-habits",
    author: "Emma Wilson",
    image: "https://placehold.co/600x400",
    date: "2024-01-12",
    category: "Health",
    summary: "Guide to maintaining a balanced diet",
    readTime: 6,
    tags: ["Health", "Food", "Wellness"],
    likes: 156,
  },
  {
    id: 5,
    title: "Travel Photography Tips",
    slug: "travel-photography-tips",
    author: "David Kim",
    image: "https://placehold.co/600x400",
    date: "2024-01-14",
    category: "Photography",
    summary: "Essential tips for travel photography",
    readTime: 7,
    tags: ["Photography", "Travel", "Art"],
    likes: 278,
  },
  {
    id: 6,
    title: "Financial Planning 101",
    slug: "financial-planning-101",
    author: "Lisa Thompson",
    image: "https://placehold.co/600x400",
    date: "2024-01-10",
    category: "Finance",
    summary: "Basic guide to personal finance",
    readTime: 9,
    tags: ["Finance", "Money", "Planning"],
    likes: 198,
  },
  {
    id: 7,
    title: "Remote Work Success",
    slug: "remote-work-success",
    author: "James Wilson",
    image: "https://placehold.co/600x400",
    date: "2024-01-09",
    category: "Career",
    summary: "How to thrive in a remote work environment",
    readTime: 7,
    tags: ["Career", "Remote Work", "Productivity"],
    likes: 234,
  },
  {
    id: 8,
    title: "Urban Gardening Guide",
    slug: "urban-gardening-guide",
    author: "Maria Garcia",
    image: "https://placehold.co/600x400",
    date: "2024-01-08",
    category: "Gardening",
    summary: "Start your own urban garden",
    readTime: 8,
    tags: ["Gardening", "Urban Living", "Nature"],
    likes: 167,
  },
  {
    id: 9,
    title: "Mental Health Awareness",
    slug: "mental-health-awareness",
    author: "Dr. Robert Brown",
    image: "https://placehold.co/600x400",
    date: "2024-01-07",
    category: "Health",
    summary: "Understanding mental health in modern times",
    readTime: 11,
    tags: ["Mental Health", "Wellness", "Health"],
    likes: 289,
  },
  {
    id: 10,
    title: "DIY Home Improvement",
    slug: "diy-home-improvement",
    author: "Anna Martinez",
    image: "https://placehold.co/600x400",
    date: "2024-01-06",
    category: "Lifestyle",
    summary: "Easy home improvement projects for beginners",
    readTime: 6,
    tags: ["DIY", "Home", "Lifestyle"],
    likes: 145,
  },
];

export const topics = Array.from(
  new Set(articlesData.flatMap((article) => article.tags))
).sort();
